// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwxaqxxuednuwflojlfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eGFxeHh1ZWRudXdmbG9qbGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTk0MjMsImV4cCI6MjA3MDE3NTQyM30.1V565TXPLzzRMBP6crA3E1DYrivQeRnw_dPdtbfb6fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Get device ID for RLS policies
const getDeviceId = (): string => {
  try {
    let deviceId = localStorage.getItem('smq.device_id');
    if (!deviceId) {
      deviceId = crypto.randomUUID();
      localStorage.setItem('smq.device_id', deviceId);
    }
    return deviceId;
  } catch (e) {
    console.error("Failed to get device ID", e);
    return crypto.randomUUID();
  }
};

// Create a proxy that automatically sets the device_id session variable
const createSecureClient = () => {
  return new Proxy(baseClient, {
    get(target, prop) {
      const originalMethod = target[prop as keyof typeof target];
      
      if (prop === 'from') {
        return (table: string) => {
          const deviceId = getDeviceId();
          // Set the session variable for RLS policies
          baseClient.rpc('set_config', {
            setting_name: 'app.device_id',
            setting_value: deviceId,
            is_local: true
          }).then(() => {}).catch(() => {}); // Silent fail to not block operations
          
          return target.from(table);
        };
      }
      
      return originalMethod;
    }
  });
};

export const supabase = createSecureClient() as typeof baseClient;