// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mobileStorage } from '@/lib/mobileStorage';
import { isNativePlatform } from '@/lib/platform';

const SUPABASE_URL = "https://lwxaqxxuednuwflojlfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eGFxeHh1ZWRudXdmbG9qbGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTk0MjMsImV4cCI6MjA3MDE3NTQyM30.1V565TXPLzzRMBP6crA3E1DYrivQeRnw_dPdtbfb6fM";

// Custom storage adapter for mobile
const customStorageAdapter = {
  getItem: async (key: string) => {
    return await mobileStorage.getItem(key);
  },
  setItem: async (key: string, value: string) => {
    await mobileStorage.setItem(key, value);
  },
  removeItem: async (key: string) => {
    await mobileStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isNativePlatform() ? customStorageAdapter : localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});